/**
 * 技术术语 → 节点路径映射
 * 用于 RichText 组件把 [[术语]] 渲染成可点击的链接
 */
export const termToPath: Record<string, string[]> = {
  // 上游
  '数据': ['upstream', 'data'],
  '芯片': ['upstream', 'chips'],
  'GPU': ['upstream', 'chips', 'gpu'],
  'TPU': ['upstream', 'chips', 'tpu'],
  'NPU': ['upstream', 'chips', 'npu'],
  '并行计算': ['upstream', 'chips'],
  '显存': ['upstream', 'chips'],
  '算力': ['upstream', 'compute'],
  '云计算': ['upstream', 'compute'],
  '云厂商': ['upstream', 'compute'],
  '训练': ['upstream', 'compute', 'training'],
  '推理': ['upstream', 'compute', 'inference'],
  '微调': ['upstream', 'compute', 'training'],
  'FLOPS': ['upstream', 'compute'],
  'TFLOPS': ['upstream', 'compute'],
  'per-token FLOPs': ['upstream', 'compute'],
  'GPU 利用率': ['upstream', 'compute'],
  '能耗': ['upstream', 'compute'],
  'CPU': ['upstream', 'chips'],
  'NVIDIA': ['upstream', 'chips'],
  'AMD': ['upstream', 'chips'],
  '华为昇腾': ['upstream', 'chips'],
  'AWS': ['upstream', 'compute'],
  'Azure': ['upstream', 'compute'],
  'Google Cloud': ['upstream', 'compute'],
  '阿里云': ['upstream', 'compute'],
  '华为云': ['upstream', 'compute'],
  '腾讯云': ['upstream', 'compute'],
  '百度云': ['upstream', 'compute'],
  '火山引擎': ['upstream', 'compute'],
  'InfiniBand': ['upstream', 'compute'],
  'RoCE': ['upstream', 'compute'],
  '高速互联': ['upstream', 'compute'],
  '高带宽互联': ['upstream', 'compute'],
  'FP8': ['upstream', 'compute'],
  '量化': ['upstream', 'compute', 'inference'],
  '批处理': ['upstream', 'compute', 'inference'],
  '连续批处理': ['upstream', 'compute', 'inference'],
  '投机采样': ['upstream', 'compute', 'inference'],
  'TTFT': ['upstream', 'compute', 'inference'],
  'TPOT': ['upstream', 'compute', 'inference'],
  '延迟': ['upstream', 'compute', 'inference'],
  '吞吐量': ['upstream', 'compute', 'inference'],
  '并发': ['upstream', 'compute', 'inference'],

  // 中游 - 通用模型概念
  'AI 模型': ['midstream', 'models'],
  '大语言模型': ['midstream', 'models'],
  'LLM': ['midstream', 'models'],
  '模型': ['midstream', 'models'],
  '参数': ['midstream', 'models'],
  '参数规模': ['midstream', 'models'],
  '总参数量': ['midstream', 'models'],
  '激活参数': ['midstream', 'models'],
  '激活比例': ['midstream', 'models'],
  '预训练': ['upstream', 'compute', 'training'],
  '推理能力': ['midstream', 'models', 'deepseek-r1'],
  '推理模型': ['midstream', 'models', 'deepseek-r1'],
  '数学推理': ['midstream', 'models', 'deepseek-r1'],
  '代码生成': ['downstream', 'applications'],
  '代码能力': ['midstream', 'models', 'deepseek-r1'],

  // 上下文 / 多模态
  '上下文': ['midstream', 'algorithms', 'long-context'],
  '上下文长度': ['midstream', 'algorithms', 'long-context'],
  '长文本': ['midstream', 'algorithms', 'long-context'],
  '长上下文': ['midstream', 'algorithms', 'long-context'],
  '长上下文技术': ['midstream', 'algorithms', 'long-context'],
  '滑动窗口': ['midstream', 'algorithms', 'long-context'],
  '外推位置编码': ['midstream', 'algorithms', 'long-context'],
  '环形注意力': ['midstream', 'algorithms', 'long-context'],
  '多模态': ['midstream', 'algorithms', 'multimodal'],
  '多模态能力': ['midstream', 'algorithms', 'multimodal'],

  // 海外模型
  'GPT': ['midstream', 'models', 'gpt-4'],
  'GPT-3.5': ['midstream', 'models', 'gpt-4'],
  'GPT-4': ['midstream', 'models', 'gpt-4'],
  'GPT-4o': ['midstream', 'models', 'gpt-4'],
  'GPT-4V': ['midstream', 'models', 'gpt-4'],
  'o1': ['midstream', 'models', 'gpt-4'],
  'OpenAI o1': ['midstream', 'models', 'gpt-4'],
  'Claude': ['midstream', 'models', 'claude'],
  'Claude 3': ['midstream', 'models', 'claude'],
  'Claude 3.5': ['midstream', 'models', 'claude'],
  'Claude Opus': ['midstream', 'models', 'claude'],
  'Claude Opus 4.8': ['midstream', 'models', 'claude'],
  'Claude Opus 4.6': ['midstream', 'models', 'claude'],
  'Gemini': ['midstream', 'models', 'gemini'],
  'Gemini 1.5 Pro': ['midstream', 'models', 'gemini'],
  'Gemini 2.0': ['midstream', 'models', 'gemini'],
  'LLaMA': ['midstream', 'models', 'llama'],
  'LLaMA 2': ['midstream', 'models', 'llama'],
  'LLaMA 3': ['midstream', 'models', 'llama'],
  'Mistral': ['midstream', 'models'],
  'Mixtral': ['midstream', 'algorithms', 'moe'],
  'Mixtral 8x7B': ['midstream', 'algorithms', 'moe'],
  'Mixtral 8x22B': ['midstream', 'algorithms', 'moe'],

  // 国产模型
  'DeepSeek': ['midstream', 'models', 'deepseek-v3'],
  'DeepSeek-V2': ['midstream', 'models', 'deepseek-v3'],
  'DeepSeek-V2.5': ['midstream', 'models', 'deepseek-v3'],
  'DeepSeek-V2/V3': ['midstream', 'models', 'deepseek-v3'],
  'DeepSeek-V3': ['midstream', 'models', 'deepseek-v3'],
  'DeepSeek V4-Pro': ['midstream', 'models', 'deepseek-v3'],
  'DeepSeek-R1': ['midstream', 'models', 'deepseek-r1'],
  '通义千问': ['midstream', 'models', 'qwen'],
  'Qwen': ['midstream', 'models', 'qwen'],
  'Qwen2': ['midstream', 'models', 'qwen'],
  'Qwen2.5': ['midstream', 'models', 'qwen'],
  'Qwen3': ['midstream', 'models', 'qwen'],
  'Qwen-VL': ['midstream', 'models', 'qwen'],
  'Qwen-Coder': ['midstream', 'models', 'qwen'],
  'Qwen-Math': ['midstream', 'models', 'qwen'],
  'Qwen-MoE': ['midstream', 'models', 'qwen'],
  'Kimi': ['midstream', 'models', 'kimi-model'],
  '月之暗面': ['midstream', 'models', 'kimi-model'],
  '智谱': ['midstream', 'models', 'glm-52'],
  '智谱 AI': ['midstream', 'models', 'glm-52'],
  'GLM': ['midstream', 'models', 'glm-52'],
  'GLM-4.5': ['midstream', 'models', 'glm-45'],
  'GLM-5': ['midstream', 'models', 'glm-5'],
  'GLM-5.2': ['midstream', 'models', 'glm-52'],
  'GLM-4-9B': ['midstream', 'algorithms', 'long-context'],
  '文心一言': ['midstream', 'models', 'wenxin'],
  '文心大模型': ['midstream', 'models', 'wenxin'],
  '豆包': ['midstream', 'models'],
  '讯飞星火': ['midstream', 'models'],
  '百川': ['midstream', 'models'],

  // 中游 - 技术
  'MoE': ['midstream', 'algorithms', 'moe'],
  '混合专家': ['midstream', 'algorithms', 'moe'],
  '专家': ['midstream', 'algorithms', 'moe'],
  'Dense': ['midstream', 'algorithms', 'moe'],
  '稠密模型': ['midstream', 'algorithms', 'moe'],
  'top-k': ['midstream', 'algorithms', 'moe'],
  '路由': ['midstream', 'algorithms', 'sigmoid-gating'],
  '门控': ['midstream', 'algorithms', 'sigmoid-gating'],
  'Sigmoid 门控': ['midstream', 'algorithms', 'sigmoid-gating'],
  'Softmax 门控': ['midstream', 'algorithms', 'sigmoid-gating'],
  'Softmax': ['midstream', 'algorithms', 'sigmoid-gating'],
  '负载均衡': ['midstream', 'algorithms', 'sigmoid-gating'],
  'MLA': ['midstream', 'algorithms', 'mla'],
  '多头潜在注意力': ['midstream', 'algorithms', 'mla'],
  '注意力': ['midstream', 'algorithms', 'mla'],
  '注意力机制': ['midstream', 'algorithms', 'mla'],
  '注意力头': ['midstream', 'algorithms', 'mla'],
  'MHA': ['midstream', 'algorithms', 'mla'],
  'MQA': ['midstream', 'algorithms', 'mla'],
  'GQA': ['midstream', 'algorithms', 'mla'],
  'KV-cache': ['midstream', 'algorithms', 'mla'],
  'KV 缓存': ['midstream', 'algorithms', 'mla'],
  'Transformer': ['midstream', 'algorithms'],
  'RLHF': ['midstream', 'algorithms', 'rlhf'],
  'DPO': ['midstream', 'algorithms', 'rlhf'],
  'GRPO': ['midstream', 'algorithms', 'rlhf'],
  'PPO': ['midstream', 'algorithms', 'rlhf'],
  'SFT': ['upstream', 'compute', 'training'],
  '监督微调': ['upstream', 'compute', 'training'],
  '强化学习': ['midstream', 'algorithms', 'rlhf'],
  '奖励模型': ['midstream', 'algorithms', 'rlhf'],
  '人类反馈': ['midstream', 'algorithms', 'rlhf'],
  '偏好数据': ['midstream', 'algorithms', 'rlhf'],
  '对齐': ['midstream', 'algorithms', 'rlhf'],
  'Constitutional AI': ['midstream', 'algorithms', 'rlhf'],
  'Chain-of-Thought': ['midstream', 'models', 'deepseek-r1'],
  '思考链': ['midstream', 'models', 'deepseek-r1'],
  '稀疏注意力': ['midstream', 'algorithms', 'dsa'],
  '线性注意力': ['midstream', 'algorithms', 'dsa'],
  'DSA': ['midstream', 'algorithms', 'dsa'],
  '动态稀疏注意力': ['midstream', 'algorithms', 'dsa'],
  'IndexShare': ['midstream', 'algorithms', 'index-share'],
  'IndexCache': ['midstream', 'algorithms', 'index-share'],
  'Indexer': ['midstream', 'algorithms', 'index-share'],
  'Muon Split': ['midstream', 'algorithms', 'muon-split'],
  'Muon': ['midstream', 'algorithms', 'muon-split'],
  'Slime': ['midstream', 'algorithms', 'slime'],
  'TITO': ['midstream', 'algorithms', 'tito'],
  'TITO Gateway': ['midstream', 'algorithms', 'tito'],
  '跨阶段蒸馏': ['midstream', 'algorithms', 'cross-stage-distillation'],
  '蒸馏': ['midstream', 'algorithms', 'cross-stage-distillation'],
  'DP-aware Routing': ['midstream', 'algorithms', 'dp-aware-routing'],

  // 下游
  '应用': ['downstream', 'applications'],
  '应用场景': ['downstream', 'applications'],
  '产品': ['downstream', 'products'],
  'ChatGPT': ['downstream', 'products', 'chatgpt'],
  'Midjourney': ['downstream', 'products'],
  'GitHub Copilot': ['downstream', 'products'],
  'Perplexity': ['downstream', 'products'],
  'DeepSeek App': ['downstream', 'products', 'deepseek-app'],
  'Kimi Chat': ['downstream', 'products', 'kimi-chat'],
  '可灵': ['downstream', 'products'],
  '即梦': ['downstream', 'products'],
  'Agent': ['downstream', 'applications'],
  '智能体': ['downstream', 'applications'],
  'AIGC': ['downstream', 'applications'],
  '生成式 AI': ['downstream', 'applications'],
  '聊天机器人': ['downstream', 'applications'],
  '图像生成': ['downstream', 'applications'],
  '视频生成': ['downstream', 'applications'],
  '代码助手': ['downstream', 'applications'],
  '编程': ['downstream', 'applications'],
  '自动驾驶': ['downstream', 'applications'],
  '推荐系统': ['downstream', 'applications'],
  '搜索': ['downstream', 'applications'],
  '写作': ['downstream', 'applications'],
  '翻译': ['downstream', 'applications'],
  '医疗': ['downstream', 'applications'],
  '教育': ['downstream', 'applications'],
  '音乐': ['downstream', 'applications'],
  '私有化部署': ['downstream', 'applications'],
  'RAG': ['downstream', 'applications'],
}

/**
 * 查找术语对应的路径。支持忽略大小写和去除空格后的匹配。
 */
export function findTermPath(term: string): string[] | undefined {
  // 直接匹配
  if (termToPath[term]) return termToPath[term]

  // 忽略大小写匹配
  const lower = term.toLowerCase()
  for (const key of Object.keys(termToPath)) {
    if (key.toLowerCase() === lower) return termToPath[key]
  }

  // 去除空格匹配
  const noSpace = term.replace(/\s+/g, '')
  for (const key of Object.keys(termToPath)) {
    if (key.replace(/\s+/g, '') === noSpace) return termToPath[key]
  }

  return undefined
}
